---
# Usage
# ansible-playbook -i $inventory_file_of_your_choice.yml playbooks/snapshot_restore.yml -e "network=mumbai client=bor"
# Supports mumbai and mainnet for networks, bor or heimdall as clients. erigon coming soon.
- name: stop heimdall service
  systemd:
    state: stopped
    daemon-reload: yes
    name: heimdalld.service
  when: client == "heimdall"
  become: yes

- name: stop bor service
  systemd:
    state: stopped
    daemon-reload: yes
    name: bor.service
  when: client == "bor"
  become: yes

- name: removing existing data for {{ client }}
  shell: sudo rm -rf /var/lib/bor/data/bor/chaindata
  when: client == "bor"

- name: removing existing data for {{ client }}
  shell: sudo rm -rf /var/lib/heimdall/data/*
  when: client == "heimdall"

- name: Copy the script to the remote host
  copy:
    src: files/snapshot_restore.sh
    dest: /home/ubuntu/snapshot_restore.sh
    owner: ubuntu
    group: ubuntu
    mode: '0755'

# Screen session has the {{ client_input }} so you can check the host with screen -r snapbor or screen -r snapheimdall in order to check status
- name: Run the snapshot restore
  shell: screen -dmS snap{{ client }} sudo /home/ubuntu/snapshot_restore.sh -n {{ network }} -c {{ client }}