---
# ansible-playbook -i inventory.yml playbooks/snapshot-restore.yml -e "network=$network client=$client"
# Networks: mumbai and mainnet
# clients: bor and heimdall. Technically you can use erigon but will be plugging that in soon enough.
# On the host, you can find the screen session with the below command:
# ps -ef | grep -i screen
# each session is screen$client, snapbor, snapheimdall, etc.
- name: snapshot restore
  hosts: all
  become: true
  roles:
    - snapshot-restore